name: Code Check
on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  group: ${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: ⬣ ESLint, ʦ TypeScript, 💅 Prettier, and 🃏 Test
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: 🤌 Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: 📥 Download deps
        run: pnpm install --frozen-lockfile

      - name: 🔬 Fix lint issues
        run: pnpm run lint:fix

      - name: 💅 Fix Prettier issues
        run: pnpm run format

      - name: 🔎 Type check
        run: pnpm run typecheck

      - name: 🃏 Run jest
        run: pnpm run test

      - name: 🚀 Commit and push fixes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --staged --quiet || (git commit -m "🔧 Auto-fix lint and formatting issues" && git push)
